"""empty message

Revision ID: 8cf8e93ee2a6
Revises: 21679d86d07f
Create Date: 2022-02-20 19:07:55.015197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf8e93ee2a6'
down_revision = '21679d86d07f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_icon', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_icon')
    # ### end Alembic commands ###
